CREATE TABLE users (
    USER_ID   BIGINT      NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR(128) NOT NULL,
    LAST_NAME VARCHAR(128) NOT NULL,
    EMAIL VARCHAR(128) NOT NULL,
    USERNAME VARCHAR(128) NOT NULL,
    STATUS BOOLEAN NOT NULL,
    PRIMARY KEY (USER_ID)
);